'use strict';
const {test,expect}=require('@playwright/test');
const {completeUnit910,completeActivity}=require('../support/unit9-10-flow');
test.use({reducedMotion:'reduce',actionTimeout:5000});
test('从带音标词卡开始，浏览14句并完成26题才取得15星课堂配套证书',async({page})=>{
 test.setTimeout(210000);
 await page.goto('/unit9-10/');await expect(page).toHaveTitle('街角问候站 · Lesson 9–10');
 await page.getByRole('button',{name:'开始冒险',exact:true}).click();await expect(page).toHaveURL(/#learn\/words$/);
 const room=page.locator('.stage-words'),hello=room.getByRole('button',{name:'hello',exact:true});
 await expect(hello).toContainText('/heˈloʊ/');await hello.click();await expect(hello.locator('.word-meaning')).toBeVisible();await expect(hello).not.toContainText('录音暂时');
 for(let i=0;i<3;i++)await room.getByRole('button',{name:'下一组词卡',exact:true}).click();await expect(room.locator('.unit-word')).toHaveCount(4);
 await room.getByRole('button',{name:'下一站：单词寻宝',exact:true}).click();await expect(page.locator('.stage-listen')).toContainText('第 1 / 13 题');await expect(page.locator('.stage-listen').getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
 await page.goto('/unit9-10/#learn/certificate');await expect(page.getByRole('button',{name:'领取单元证书',exact:true})).toBeDisabled();
 await completeUnit910(page);await page.getByRole('textbox',{name:'证书上的名字',exact:true}).fill('暖心的小伙伴');await page.getByRole('button',{name:'领取单元证书',exact:true}).click();const dialog=page.getByRole('dialog',{name:'街角问候站纪念',exact:true});await expect(dialog.locator('#certificateName')).toHaveText('暖心的小伙伴');
 const day=await dialog.locator('#certificateDate').innerText();await dialog.screenshot({path:'output/playwright/unit9-10/certificate-desktop.png'});const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'保存图片',exact:true}).click();await(await download).saveAs('output/playwright/unit9-10/certificate-saved.png');const pdf=await page.pdf({path:'output/playwright/unit9-10/certificate-print.pdf',preferCSSPageSize:true,printBackground:true});expect(pdf.toString('latin1').match(/\/Type \/Page\b/g)).toHaveLength(1);
 await page.keyboard.press('Escape');await page.reload();await page.getByRole('button',{name:'领取单元证书',exact:true}).click();await expect(dialog.locator('#certificateDate')).toHaveText(day);await page.keyboard.press('Escape');for(const other of ['unit1-2','unit3-4','unit5-6','unit7-8','unit49-50']){await page.goto('/'+other+'/#learn/certificate');await expect(page.locator('#starCount')).toHaveText('0');}
});

test('首页与 lesson 子目录进入问候站，独立恢复草稿并定位同一地址',async({page})=>{
 const failed=[];page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
 await page.goto('/lesson/');await page.getByRole('link',{name:'开始学习：街角问候站',exact:true}).click();await expect(page).toHaveURL(/\/lesson\/unit9-10\/#learn\/words$/);
 await page.getByRole('link',{name:'看一看，说一说',exact:true}).click();const room=page.locator('.stage-describe');await room.getByRole('button',{name:"He's",exact:true}).click();await page.locator('#startBtn').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'继续冒险',exact:true}).click();await expect(room.getByRole('heading').first()).toBeInViewport();
 await page.getByRole('link',{name:'我的课程',exact:true}).click();await expect(page.getByRole('link',{name:'继续学习：街角问候站',exact:true})).toHaveAttribute('href','/lesson/unit9-10/#learn/describe');await expect(page.getByRole('link',{name:'开始学习：新朋友采访站',exact:true})).toBeVisible();await page.getByRole('link',{name:'继续学习：街角问候站',exact:true}).click();await expect(room.getByRole('button',{name:"He's",exact:true})).toHaveAttribute('aria-pressed','true');
 await page.goto('/unit9-10/#learn/describe');await expect(room.getByRole('button',{name:"He's",exact:true})).toHaveAttribute('aria-pressed','false');expect(failed).toEqual([]);
});

test('纸笔保留教材 A 六题与 B 十二题，真实输出一张有足够书写空间的 A4',async({page})=>{
 await page.goto('/unit9-10/#learn/certificate');await page.getByText('和朋友再试试',{exact:true}).click();await expect(page.locator('.reference-writing li')).toHaveText(["Mr. Blake isn't a student. ___ a teacher.","This isn't my umbrella. ___ your umbrella.","Sophie isn't a teacher. ___ a keyboard operator.","Steven isn't cold. ___ hot.","Naoko isn't Chinese. ___ Japanese.","This isn't a German car. ___ a Swedish car."]);
 await expect(page.locator('.reply-writing li>span:first-child')).toHaveText(['that man / fat · he','that woman / thin · she','that policeman / tall · he','that policewoman / short · she','that mechanic / dirty · he','that nurse / clean · she','Steven / hot · he','Emma / cold · she','that milkman / old · he','that air hostess / young · she','that hairdresser / busy · he','that housewife / lazy · she']);await page.evaluate(()=>{window.print=()=>{};});await page.getByRole('button',{name:'打印练习纸',exact:true}).click();await page.emulateMedia({media:'print',reducedMotion:'reduce'});
 for(const row of await page.locator('.reply-writing li').all()){await expect(row).toBeVisible();await expect(row.locator('.writing-rule')).toHaveCount(2);expect(await row.evaluate(el=>[...el.querySelectorAll('.writing-rule')].every(line=>line.getBoundingClientRect().height>=19&&line.clientWidth>=el.clientWidth*.9))).toBe(true);}
 const pdf=await page.pdf({path:'output/playwright/unit9-10/writing-print.pdf',preferCSSPageSize:true,printBackground:true});expect(pdf.toString('latin1').match(/\/Type \/Page\b/g)).toHaveLength(1);
});

test('挑战错答、提示、暂停刷新与独立拼句分别记录，不提前发证',async({page})=>{
 test.setTimeout(45000);await page.goto('/unit9-10/#learn/exam');const room=page.locator('.stage-exam'),check=room.getByRole('button',{name:'检查答案',exact:true});await room.getByRole('button',{name:'Tony · cold',exact:true}).click();await expect(check).toBeEnabled({timeout:10000});await check.click();await expect(room.getByRole('status')).toHaveText('再看看，试一次。');await room.getByRole('button',{name:'再试一次',exact:true}).click();await room.getByRole('button',{name:'Tony · fine',exact:true}).click();await expect(check).toBeEnabled({timeout:10000});await check.click();await room.getByRole('button',{name:'下一题',exact:true}).click();
 await room.getByRole('button',{name:'给点线索',exact:true}).click();await room.getByRole('button',{name:'他不觉得冷',exact:true}).click();await room.getByRole('button',{name:'暂停，稍后继续',exact:true}).click();await page.reload();await room.getByRole('button',{name:'继续挑战',exact:true}).click();await expect(room.getByRole('button',{name:'他不觉得冷',exact:true})).toHaveAttribute('aria-pressed','true');await check.click();await room.getByRole('button',{name:'下一题',exact:true}).click();for(const token of ['Look at','that umbrella.',"It's",'dirty.'])await room.getByRole('group',{name:'待选词块',exact:true}).getByRole('button',{name:token,exact:true}).click();await check.click();await room.getByRole('button',{name:'查看本次记录',exact:true}).click();await expect(room).toContainText('首次独立答对 1 / 3');await expect(room).toContainText('提示后完成 1 题 · 修正后完成 1 题');await page.goto('/unit9-10/#learn/certificate');await expect(page.locator('#starCount')).toHaveText('3');await expect(page.getByRole('button',{name:'领取单元证书',exact:true})).toBeDisabled();
});

test('内容升版使被改活动失效，其他活动草稿保留；不会套用旧答案',async({page})=>{
 await page.goto('/unit9-10/#learn/reply');const reply=page.locator('.stage-reply');await reply.getByRole('button',{name:"I'm fine, thanks.",exact:true}).click();await reply.getByRole('button',{name:'检查答案',exact:true}).click();await page.goto('/unit9-10/#learn/describe');const describe=page.locator('.stage-describe');await describe.getByRole('button',{name:"He's",exact:true}).click();await page.route('**/unit9-10/content.js*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace("q('reply-well'","q('reply-well-revised'")});});await page.reload();await expect(describe.getByRole('button',{name:"He's",exact:true})).toHaveAttribute('aria-pressed','true');await page.goto('/unit9-10/#learn/reply');await expect(reply.getByRole('button',{name:"I'm fine, thanks.",exact:true})).toHaveAttribute('aria-pressed','false');await expect(reply.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await expect(reply.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
});

test('重开冒险包含新单元；取消保留，确认仅清理本网站路径记录',async({page})=>{
 await page.goto('/unit9-10/#learn/describe');const room=page.locator('.stage-describe');await room.getByRole('button',{name:"He's",exact:true}).click();for(const path of ['unit1-2/#learn/ask','unit3-4/#learn/reply','unit5-6/#learn/refer','unit7-8/#learn/be','unit9-10/#learn/describe','unit49-50/#learn/give']){await page.goto('/lesson/'+path);await expect(page.locator('.stage-'+path.split('#learn/')[1])).toBeVisible();}await page.goto('/lesson/');await page.getByRole('button',{name:'设备冒险设置',exact:true}).click();await page.getByRole('button',{name:'重开冒险',exact:true}).click();await page.getByRole('button',{name:'继续确认',exact:true}).click();await page.getByRole('button',{name:'取消重开',exact:true}).click();await page.getByRole('button',{name:'返回课程',exact:true}).click();await expect(page.getByRole('link',{name:'继续学习：街角问候站',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'设备冒险设置',exact:true}).click();await page.getByRole('button',{name:'重开冒险',exact:true}).click();await page.getByRole('button',{name:'继续确认',exact:true}).click();await page.getByRole('button',{name:'确认重开',exact:true}).click();for(const name of ['礼貌小帮手','雨伞认领小帮手','新朋友见面会','新朋友采访站','街角问候站'])await expect(page.getByRole('link',{name:'开始学习：'+name,exact:true})).toBeVisible();await page.goto('/unit9-10/#learn/describe');await expect(room.getByRole('button',{name:"He's",exact:true})).toHaveAttribute('aria-pressed','true');
});

test('短屏单词练习末题与重练都能操作，重练清本轮答案并保留已得星星',async({page})=>{
 test.setTimeout(90000);await page.setViewportSize({width:390,height:500});await completeActivity(page,'listen');const room=page.locator('.stage-listen');await expect(page.locator('#starCount')).toHaveText('3');await room.getByRole('button',{name:'再练一轮',exact:true}).click();await expect(room).toContainText('第 1 / 13 题');await expect(room.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await expect(room.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await expect(room.locator('.practice-options [aria-pressed="true"]')).toHaveCount(0);await page.reload();await expect(room.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await expect(page.locator('#starCount')).toHaveText('3');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
