'use strict';
const{test,expect}=require('@playwright/test'),fs=require('node:fs/promises');
const{DIALOGUE,ANSWERS,WRONG,select,advance,activity,story,complete}=require('../support/unit37-38-flow');
const OUT='output/playwright/unit37-38';test.use({reducedMotion:'reduce'});test.beforeAll(()=>fs.mkdir(OUT,{recursive:true}));
test('入口横幅、11张词卡音标与翻页恢复',async({page})=>{
 await page.goto('/');await page.getByRole('link',{name:'开始学习：书架制作小工坊',exact:true}).click();await expect(page).toHaveURL(/unit37-38\/#learn\/words$/);const r=page.locator('.stage-words');const words=['work','hard','make','bookcase','hammer','paint','pink','favourite','homework','listen','dish'];const ipa=['/wɜːk/','/hɑːd/','/meɪk/','/ˈbʊkkeɪs/','/ˈhæmə/','/peɪnt/','/pɪŋk/','/ˈfeɪvərɪt/','/ˈhəʊmwɜːk/','/ˈlɪsən/','/dɪʃ/'];
 for(let i=0;i<11;i++){if(i===6)await r.getByRole('button',{name:'下一组词卡',exact:true}).click();const card=r.getByRole('button',{name:words[i],exact:true});await expect(card.locator('.word-phonetic')).toHaveText(ipa[i]);const bounds=await card.boundingBox();await card.click();await expect(card.locator('.word-meaning')).toBeVisible();expect((await card.boundingBox()).height).toBe(bounds.height);await card.click();}await page.reload();await expect(r.locator('#wordPageProgress')).toHaveText('2 / 2');await r.getByRole('button',{name:'下一站：单词寻宝',exact:true}).click();await page.getByRole('link',{name:'我的课程',exact:true}).click();await expect(page.getByRole('link',{name:'继续学习：书架制作小工坊',exact:true})).toHaveAttribute('href','/unit37-38/#learn/listen');
});
test('全部声音失败仍可完成33题18句并导出纪念证书',async({page})=>{
 test.setTimeout(180000);await page.setViewportSize({width:1280,height:1200});const voices=[],errors=[];page.on('request',r=>{if(/\/(audio|voices)\//.test(r.url()))voices.push(r.url());});page.on('pageerror',e=>errors.push(e.message));await page.route(/\.(mp3|ogg|wav)(\?|$)/,r=>r.abort());await page.addInitScript(()=>{globalThis.voiceCalls=0;speechSynthesis.speak=()=>globalThis.voiceCalls++;HTMLMediaElement.prototype.play=()=>Promise.reject(Error('sound unavailable'));});
 await activity(page,'listen');await page.locator('.stage-listen').screenshot({path:OUT+'/finish-listen.png'});await story(page);await page.locator('.stage-text').screenshot({path:OUT+'/finish-text.png'});for(const id of ['roles','observe','be','trans','exam']){await activity(page,id);await page.locator('.stage-'+id).screenshot({path:OUT+'/finish-'+id+'.png'});}await page.goto('/unit37-38/#learn/certificate');await expect(page.locator('#starCount')).toHaveText('15');await page.getByRole('textbox',{name:'证书上的名字',exact:true}).fill('工坊小发现者');await page.getByRole('button',{name:'领取单元证书',exact:true}).click();const d=page.getByRole('dialog',{name:'工坊纪念',exact:true});await expect(d).toContainText('完成 Lesson 37–38 课堂配套练习');const download=page.waitForEvent('download');await d.getByRole('button',{name:'保存图片',exact:true}).click();await(await download).saveAs(OUT+'/certificate.png');await page.screenshot({path:OUT+'/certificate-page.png'});await page.emulateMedia({media:'print'});await page.pdf({path:OUT+'/certificate.pdf',format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});await page.keyboard.press('Escape');await page.reload();await expect(page.locator('#starCount')).toHaveText('15');await expect(page.getByRole('textbox',{name:'证书上的名字',exact:true})).toHaveValue('工坊小发现者');expect(voices).toEqual([]);expect(errors).toEqual([]);expect(await page.evaluate(()=>voiceCalls)).toBe(0);
});
test('18句原文、历史中文稳定，锤子拒绝确认交接与计划分镜',async({page})=>{
 await page.setViewportSize({width:1280,height:1200});await page.goto('/unit37-38/#learn/roles');await page.getByRole('button',{name:'先看课文',exact:true}).click();const r=page.locator('.stage-text');let y;
 for(let i=0;i<18;i++){await r.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();await expect(r.locator('.btext span')).toHaveText(DIALOGUE.slice(0,i+1));const line=r.locator('.classroom-illustration');await expect(line.locator('[data-prop="big-delivered"]')).toBeVisible({visible:i>=8});await expect(line.locator('[data-prop="big-hook"]')).toBeVisible({visible:i<8});await expect(line.locator('[data-prop="small-offered"]')).toBeVisible({visible:i===5});await expect(line.locator('[data-prop="pink-plan"]')).toBeVisible({visible:i>=13});if([0,3,5,6,7,8,10,13,17].includes(i)){await r.getByRole('button',{name:'看中文',exact:true}).last().click();await r.screenshot({path:OUT+'/story-'+i+'.png'});}const nextY=await r.locator('.stage-ctrl').evaluate(e=>e.getBoundingClientRect().top+scrollY);if(y===undefined)y=nextY;else expect(Math.abs(y-nextY)).toBeLessThan(2);if(i===7){await page.reload();await expect(r.locator('.btext')).toHaveCount(8);await expect(line.locator('[data-prop="big-delivered"]')).toBeHidden();}}
 await expect(page.locator('#starCount')).toHaveText('0');await r.getByRole('button',{name:'完成课文',exact:true}).click();await expect(page.locator('#starCount')).toHaveText('1');await r.getByRole('button',{name:'再看一遍',exact:true}).click();await page.reload();await expect(r.locator('.btext')).toHaveCount(0);await expect(r.locator('[data-prop="big-delivered"]')).toBeHidden();
});
test('工具与接收者双条件，未检查和错答不交接，修正与重练',async({page})=>{
 await page.setViewportSize({width:1280,height:1200});await story(page);await page.goto('/unit37-38/#learn/roles');const r=page.locator('.stage-roles');await select(r,'制作书架');await r.getByRole('button',{name:'检查答案',exact:true}).click();await advance(r,false);await r.screenshot({path:OUT+'/handoff-before.png'});await r.getByRole('button',{name:'大锤子',exact:true}).click();await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await r.getByRole('button',{name:'Dan',exact:true}).click();await expect(r.locator('.handoff-arrived')).toHaveCount(0);await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await r.screenshot({path:OUT+'/handoff-wrong.png'});await page.reload();await expect(r.locator('.handoff-arrived')).toHaveCount(0);await r.getByRole('button',{name:'再试一次',exact:true}).click();await r.getByRole('button',{name:'给点线索',exact:true}).click();await expect(r.locator('.practice-hint')).toContainText('me');await r.getByRole('button',{name:'George',exact:true}).click();await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.locator('.handoff-arrived')).toHaveCount(1);await expect(r.getByRole('button',{name:'George',exact:true}).locator('.handoff-arrived')).toBeVisible();await r.screenshot({path:OUT+'/handoff-correct.png'});await advance(r,false);await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
});
test('综合16题逐题错答再修正，暂停刷新与词块撤回',async({page})=>{
 test.setTimeout(150000);await page.goto('/unit37-38/#learn/exam');const r=page.locator('.stage-exam');for(const[i,a]of ANSWERS.exam.entries()){
 await expect(r).toContainText(`第 ${i+1} / 16 题`);await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();if(i<2)await r.screenshot({path:OUT+'/exam-before-'+i+'.png'});await select(r,WRONG[i]);await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await expect(r.locator('.is-correct')).toHaveCount(0);if(i<2)await r.screenshot({path:OUT+'/exam-wrong-'+i+'.png'});if(i===15){await page.reload();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');}await r.getByRole('button',{name:'再试一次',exact:true}).click();if(Array.isArray(a)){const chosen=r.getByRole('group',{name:'已选词块',exact:true});while(await chosen.getByRole('button').count())await chosen.getByRole('button').first().click();}await select(r,a);if(i===0){await r.getByRole('button',{name:'暂停，稍后继续',exact:true}).click();await page.reload();await expect(r).toContainText('已暂停 · 第 1 / 16 题');await r.getByRole('button',{name:'继续挑战',exact:true}).click();await expect(r.getByRole('button',{name:'bookcase',exact:true})).toHaveAttribute('aria-pressed','true');}await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('答对了！');if(i<2)await r.screenshot({path:OUT+'/exam-correct-'+i+'.png'});await expect(r.getByRole('progressbar')).toHaveAttribute('aria-valuenow',String(i+1));if(i===15)await expect(page.locator('#starCount')).toHaveText('0');await advance(r,i===15,true);}
 await expect(r).toContainText('修正后完成 16 题');await r.screenshot({path:OUT+'/challenge-complete.png'});await r.getByRole('button',{name:'再练一轮',exact:true}).click();await page.reload();await expect(r.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
});
for(const width of [320,390,768,1280])test(`宽度${width}工坊、六组12句对照、词卡与交接完整`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:width<700?900:1200});await page.goto('/unit37-38/#learn/text');const r=page.locator('.stage-text');for(let i=0;i<18;i++){await r.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();if([3,5,8,10,13,17].includes(i)){await r.getByRole('button',{name:'看中文',exact:true}).last().click();await r.screenshot({path:OUT+'/theatre-'+width+'-'+i+'.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);expect(await r.locator('.dialogue-log').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThan(2);}}await r.getByRole('button',{name:'完成课文',exact:true}).click();
 await page.goto('/unit37-38/#learn/models');const m=page.locator('.stage-models');for(let i=0;i<6;i++){await expect(m.locator('.reference-card')).toHaveCount(2);await expect.poll(()=>m.locator('img').evaluateAll(a=>a.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);await m.screenshot({path:OUT+'/gallery-'+width+'-'+i+'.png'});if(i<5)await m.getByRole('button',{name:'下一页动作',exact:true}).click();}await expect(m.locator('.reference-card').last()).toContainText('Now I’m washing the dishes.');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
 await page.goto('/unit37-38/#learn/observe');const o=page.locator('.stage-observe');await o.screenshot({path:OUT+'/plan-before-'+width+'.png'});await select(o,'画面一');await o.getByRole('button',{name:'检查答案',exact:true}).click();await o.screenshot({path:OUT+'/plan-wrong-'+width+'.png'});await o.getByRole('button',{name:'再试一次',exact:true}).click();await select(o,'画面二');await o.getByRole('button',{name:'检查答案',exact:true}).click();await o.screenshot({path:OUT+'/plan-correct-'+width+'.png'});
 await page.goto('/unit37-38/#learn/roles');const h=page.locator('.stage-roles');await select(h,'制作书架');await h.getByRole('button',{name:'检查答案',exact:true}).click();await advance(h,false);await h.screenshot({path:OUT+'/handoff-before-'+width+'.png'});await select(h,{handoff:['小锤子','Dan']});await h.getByRole('button',{name:'检查答案',exact:true}).click();await h.screenshot({path:OUT+'/handoff-wrong-'+width+'.png'});await h.getByRole('button',{name:'再试一次',exact:true}).click();await select(h,{handoff:['大锤子','George']});await h.getByRole('button',{name:'检查答案',exact:true}).click();await h.screenshot({path:OUT+'/handoff-correct-'+width+'.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
 await page.goto('/unit37-38/#learn/words');await page.locator('.stage-words').screenshot({path:OUT+'/words-'+width+'.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
});
test('配对部分选择不通过，错答草稿刷新后可修正',async({page})=>{
 await page.goto('/unit37-38/#learn/listen');const r=page.locator('.stage-listen');await select(r,{match:[['bookcase','锤子']]});await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await select(r,{match:[['hammer','书架'],['dish','盘子']]});await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await page.reload();await r.getByRole('button',{name:'再试一次',exact:true}).click();await select(r,{match:[['bookcase','书架'],['hammer','锤子']]});await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('答对了！');
});
test('正常反馈音与键盘；A4组B5组原纸笔练习打印',async({page})=>{
 await page.addInitScript(()=>{globalThis.completedSounds=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){this.addEventListener('ended',()=>globalThis.completedSounds.push(this.currentSrc),{once:true});return play.call(this);};globalThis.print=()=>globalThis.printRequested=true;});await page.goto('/unit37-38/#learn/observe');const r=page.locator('.stage-observe');await r.getByRole('button',{name:'画面一',exact:true}).press('Enter');await r.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>completedSounds.length)).toBe(1);await r.getByRole('button',{name:'再试一次',exact:true}).press('Enter');await r.getByRole('button',{name:'画面二',exact:true}).press('Enter');await r.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>completedSounds.length)).toBe(2);await page.goto('/unit37-38/#learn/certificate');await page.locator('#unitWriting>summary').click();await expect(page.locator('.reference-writing>li')).toHaveCount(4);await expect(page.locator('.reply-writing>li')).toHaveCount(5);await page.getByRole('button',{name:'打印练习纸',exact:true}).click();await expect.poll(()=>page.evaluate(()=>printRequested)).toBe(true);await page.emulateMedia({media:'print'});await page.pdf({path:OUT+'/writing.pdf',format:'A4',printBackground:true});
});
test('完整缓存首访与离线重访保持词卡和画册',async({page,context})=>{
 test.setTimeout(90000);await page.goto('/lesson/unit37-38/#learn/words');await expect(page.locator('#courseLoader')).toBeHidden({timeout:60000});await page.locator('.stage-words').getByRole('button',{name:'下一组词卡',exact:true}).click();await context.setOffline(true);await page.reload();await expect(page.locator('#courseLoader')).toBeHidden({timeout:30000});await expect(page.locator('#wordPageProgress')).toHaveText('2 / 2');await page.goto('/lesson/unit37-38/#learn/models');for(let i=0;i<5;i++)await page.locator('.stage-models').getByRole('button',{name:'下一页动作',exact:true}).click();await expect.poll(()=>page.locator('.stage-models img').evaluateAll(a=>a.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);await context.setOffline(false);
});
test('缺图保持准备页，重试后完整进入',async({page})=>{
 test.setTimeout(60000);await page.route(/\/hammer\.svg(?:\?|$)/,r=>r.abort());await page.goto('/lesson/unit37-38/#learn/words');await expect(page.locator('#courseLoader')).toBeVisible();await expect(page.getByRole('button',{name:'再试一次',exact:true})).toBeVisible({timeout:45000});await expect(page.locator('.stage-words')).not.toBeVisible();await page.unroute(/\/hammer\.svg(?:\?|$)/);await page.getByRole('button',{name:'再试一次',exact:true}).click();await expect(page.locator('#courseLoader')).toBeHidden({timeout:45000});await expect.poll(()=>page.locator('.stage-words img').evaluateAll(a=>a.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);
});
test('禁用常驻缓存仍可完成并导出完整证书',async({browser})=>{
 test.setTimeout(120000);const c=await browser.newContext({serviceWorkers:'block'});try{const page=await c.newPage();await complete(page,'/lesson');await page.getByRole('button',{name:'领取单元证书',exact:true}).click();const d=page.getByRole('dialog',{name:'工坊纪念',exact:true});const download=page.waitForEvent('download');await d.getByRole('button',{name:'保存图片',exact:true}).click();await(await download).saveAs(OUT+'/certificate-fallback.png');}finally{await c.close();}
});

test('矮屏电脑对话、人物与下一句同时可见，连续阅读不跳动',async({page})=>{
 await page.setViewportSize({width:1280,height:720});await page.goto('/unit37-38/#learn/text');const r=page.locator('.stage-text');
 for(let i=0;i<14;i++){await r.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();const current=r.locator('.bubble-row').last();await expect(current.locator('.btext')).toBeInViewport({ratio:1});await expect(r.getByRole('button',{name:'下一句',exact:true})).toBeInViewport({ratio:1});await expect(r.locator('[data-actor="george"]')).toBeInViewport({ratio:0.99});}
 await page.screenshot({path:OUT+'/theatre-short-screen.png'});
});
