'use strict';
const {test,expect}=require('@playwright/test'),fs=require('node:fs/promises');
const {DIALOGUE,ANSWERS,WRONG,select,advance,activity,story,complete}=require('../support/unit35-36-flow');
const OUT='output/playwright/unit35-36';test.use({reducedMotion:'reduce'});test.beforeAll(()=>fs.mkdir(OUT,{recursive:true}));
test('横幅入口、16张词卡音标与释义完整，刷新与回首页继续',async({page})=>{
 await page.goto('/');await page.getByRole('link',{name:'开始学习：村庄相册探险',exact:true}).click();await expect(page).toHaveURL(/unit35-36\/#learn\/words$/);const room=page.locator('.stage-words');
 for(let g=0;g<3;g++){await expect(room.locator('.unit-word')).toHaveCount(g===2?4:6);for(const card of await room.locator('.unit-word').all()){await expect(card.locator('.word-phonetic')).toBeVisible();await expect.poll(()=>card.locator('img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);const before=await card.boundingBox();await card.click();await expect(card.locator('.word-meaning')).toBeVisible();expect((await card.boundingBox()).height).toBe(before.height);await card.click();}if(g<2)await room.getByRole('button',{name:'下一组词卡',exact:true}).click();}
 await page.reload();await expect(room.locator('#wordPageProgress')).toHaveText('3 / 3');await room.getByRole('button',{name:'下一站：单词寻宝',exact:true}).click();await expect(page.locator('.stage-listen h3').first()).toBeInViewport();await page.getByRole('link',{name:'我的课程',exact:true}).click();await expect(page.getByRole('link',{name:'继续学习：村庄相册探险',exact:true})).toHaveAttribute('href','/unit35-36/#learn/listen');
});
test('断音完整35题与15句原文得到15星，纪念证书PNG与打印',async({page})=>{
 test.setTimeout(180000);await page.setViewportSize({width:1280,height:1200});const errors=[],voices=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/\/(audio|voices)\//.test(r.url()))voices.push(r.url());});await page.route(/\.(mp3|ogg|wav)(\?|$)/,r=>r.abort());await page.addInitScript(()=>{globalThis.voiceCalls=0;speechSynthesis.speak=()=>globalThis.voiceCalls++;HTMLMediaElement.prototype.play=()=>Promise.reject(Error('sound unavailable'));});
 await activity(page,'listen');await page.locator('.stage-listen').screenshot({path:OUT+'/finish-listen.png'});await story(page);await page.goto('/unit35-36/#learn/text');await page.locator('.stage-text').screenshot({path:OUT+'/finish-text.png'});for(const id of ['roles','observe','be','trans','exam']){await activity(page,id);await page.locator('.stage-'+id).screenshot({path:OUT+'/finish-'+id+'.png'});}await page.goto('/unit35-36/#learn/certificate');await expect(page.locator('#starCount')).toHaveText('15');await page.getByRole('textbox',{name:'证书上的名字',exact:true}).fill('村庄小观察员');await page.getByRole('button',{name:'领取单元证书',exact:true}).click();const dialog=page.getByRole('dialog',{name:'村庄相册纪念',exact:true});await expect(dialog).toContainText('完成 Lesson 35–36 课堂配套练习');await expect(dialog).not.toContainText('听力');const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'保存图片',exact:true}).click();await(await pending).saveAs(OUT+'/certificate.png');await page.screenshot({path:OUT+'/certificate-page.png'});await page.emulateMedia({media:'print'});await page.pdf({path:OUT+'/certificate.pdf',format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});await page.keyboard.press('Escape');await page.reload();await expect(page.locator('#starCount')).toHaveText('15');await expect(page.getByRole('textbox',{name:'证书上的名字',exact:true})).toHaveValue('村庄小观察员');expect(errors).toEqual([]);expect(voices).toEqual([]);expect(await page.evaluate(()=>voiceCalls)).toBe(0);
});
test('部分配对不能提交、错答不揭底，刷新后可原题修正',async({page})=>{
 await page.goto('/unit35-36/#learn/listen');const r=page.locator('.stage-listen');await select(r,{match:[['photograph','村庄']]});await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await select(r,{match:[['village','照片'],['valley','山谷']]});await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await expect(r.locator('.is-correct')).toHaveCount(0);await page.reload();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await r.getByRole('button',{name:'再试一次',exact:true}).click();await select(r,{match:[['photograph','照片'],['village','村庄']]});await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('答对了！');await advance(r,false);await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
});
test('叙述历史、最长句和翻译内部滚动，按钮稳定；末句不自动完成',async({page})=>{
 await page.goto('/unit35-36/#learn/roles');await page.getByRole('button',{name:'先看课文',exact:true}).click();const r=page.locator('.stage-text');let top;
 for(let i=0;i<15;i++){await r.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();await expect(r.locator('.btext span')).toHaveText(DIALOGUE.slice(0,i+1));if([0,3,5,8,12,13,14].includes(i)){await r.getByRole('button',{name:'看中文',exact:true}).last().click();await r.screenshot({path:OUT+'/story-'+i+'.png'});}const y=await r.locator('.stage-ctrl').evaluate(e=>e.getBoundingClientRect().top+scrollY);if(top===undefined)top=y;else expect(Math.abs(y-top)).toBeLessThan(2);if(i===5){await page.reload();await expect(r.locator('.btext')).toHaveCount(6);}}
 await expect(page.locator('#starCount')).toHaveText('0');await r.getByRole('button',{name:'完成课文',exact:true}).click();await expect(page.locator('#starCount')).toHaveText('1');await r.getByRole('button',{name:'再看一遍',exact:true}).click();await page.reload();await expect(r.locator('.btext')).toHaveCount(0);
});
test('综合16题逐题答错和修正，刷新续答、撤回词块、末题确认与重练',async({page})=>{
 test.setTimeout(180000);await page.goto('/unit35-36/#learn/exam');const r=page.locator('.stage-exam');
 for(const [i,answer]of ANSWERS.exam.entries()){
  await expect(r).toContainText(`第 ${i+1} / 16 题`);await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();if([1,5,7,9,10].includes(i))await r.screenshot({path:OUT+'/exam-before-'+i+'.png'});await select(r,WRONG[i]);await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await expect(r.locator('.is-correct')).toHaveCount(0);if([1,5,7,9,10,14,15].includes(i))await r.screenshot({path:OUT+'/exam-wrong-'+i+'.png'});if(i===15){await page.reload();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');}
  await r.getByRole('button',{name:'再试一次',exact:true}).click();if(Array.isArray(answer)){const chosen=r.getByRole('group',{name:'已选词块',exact:true});while(await chosen.getByRole('button').count())await chosen.getByRole('button').first().click();}await select(r,answer);
  if(i===0){await expect(r.getByRole('button',{name:'暂停，稍后继续',exact:true})).toHaveCount(0);await page.reload();await expect(r.locator('.progress-copy')).toHaveText('第 1 / 16 题');await expect(r.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await expect(r.getByRole('button',{name:'between',exact:true})).toHaveAttribute('aria-pressed','true');}
  await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('答对了！');await expect(r.getByRole('progressbar')).toHaveAttribute('aria-valuenow',String(i+1));if([1,5,7,9,10].includes(i))await r.screenshot({path:OUT+'/exam-correct-'+i+'.png'});if(i===15)await expect(page.locator('#starCount')).toHaveText('0');await advance(r,i===15,true);
 }
 await expect(r).toContainText('修正后完成 16 题');await r.screenshot({path:OUT+'/challenge-complete.png'});await expect(page.locator('#starCount')).toHaveText('3');await r.getByRole('button',{name:'再练一轮',exact:true}).click();await page.reload();await expect(r.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
});
for(const width of [320,390,768,1280])test(`宽度${width}三张照片、对照图、画册和词卡完整`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:width>=768?1200:900});await page.goto('/unit35-36/#learn/text');const r=page.locator('.stage-text');
 for(let i=0;i<15;i++){await r.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();if([3,8,12,13,14].includes(i)){await r.getByRole('button',{name:'看中文',exact:true}).last().click();await r.screenshot({path:OUT+'/photo-'+width+'-'+i+'.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);expect(await r.locator('.dialogue-log').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThan(2);}}
 await page.goto('/unit35-36/#learn/observe');const o=page.locator('.stage-observe');await o.screenshot({path:OUT+'/direction-before-'+width+'.png'});await o.getByRole('button',{name:'照片一',exact:true}).press('Enter');await o.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect(o.getByRole('status')).toHaveText('再看看，试一次。');await o.screenshot({path:OUT+'/direction-wrong-'+width+'.png'});await o.getByRole('button',{name:'再试一次',exact:true}).press('Enter');await o.getByRole('button',{name:'照片三',exact:true}).press('Enter');await o.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect(o.getByRole('status')).toHaveText('答对了！');await o.screenshot({path:OUT+'/direction-correct-'+width+'.png'});await advance(o,false);await expect.poll(()=>o.locator('.practice-scene').evaluate(e=>e.getBoundingClientRect().height)).toBeGreaterThan(300);await o.screenshot({path:OUT+'/routes-'+width+'.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
 await page.goto('/unit35-36/#learn/models');const m=page.locator('.stage-models');for(let i=0;i<4;i++){await expect(m.locator('.reference-card')).toHaveCount(3);await expect.poll(()=>m.locator('img').evaluateAll(imgs=>imgs.every(im=>im.complete&&im.naturalWidth>0))).toBe(true);await m.screenshot({path:OUT+'/gallery-'+width+'-'+i+'.png'});if(i<3)await m.getByRole('button',{name:'下一页路线',exact:true}).click();}await expect(m.locator('.reference-card').last()).toContainText('The man and the woman are reading in the living room.');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
 await page.goto('/unit35-36/#learn/words');const words=page.locator('.stage-words');await words.getByRole('button',{name:'photograph',exact:true}).click();await words.screenshot({path:OUT+'/words-'+width+'.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
});
test('缓存首次准备、热重访离线翻卡及画册图片就绪',async({page,context})=>{
 test.setTimeout(120000);await page.goto('/lesson/unit35-36/#learn/words');await expect(page.locator('#courseLoader')).toBeHidden({timeout:60000});await page.locator('.stage-words').getByRole('button',{name:'下一组词卡',exact:true}).click();await context.setOffline(true);await page.reload();await expect(page.locator('#courseLoader')).toBeHidden({timeout:30000});await expect(page.locator('#wordPageProgress')).toHaveText('2 / 3');await page.goto('/lesson/unit35-36/#learn/models');for(let i=0;i<3;i++)await page.locator('.stage-models').getByRole('button',{name:'下一页路线',exact:true}).click();await expect.poll(()=>page.locator('.stage-models .reference-card img').evaluateAll(imgs=>imgs.every(im=>im.complete&&im.naturalWidth>0))).toBe(true);await context.setOffline(false);
});
test('正常反馈音与键盘作答；教材A3/B12纸笔练习完整打印',async({page})=>{
 await page.addInitScript(()=>{globalThis.completedSounds=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){this.addEventListener('ended',()=>globalThis.completedSounds.push(this.currentSrc),{once:true});return play.call(this);};globalThis.print=()=>globalThis.printRequested=true;});await page.goto('/unit35-36/#learn/observe');const o=page.locator('.stage-observe');await o.getByRole('button',{name:'照片一',exact:true}).press('Enter');await o.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>completedSounds.length)).toBe(1);await o.getByRole('button',{name:'再试一次',exact:true}).press('Enter');await o.getByRole('button',{name:'照片三',exact:true}).press('Enter');await o.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>completedSounds.length)).toBe(2);await page.goto('/unit35-36/#learn/certificate');await page.locator('#unitWriting>summary').click();await expect(page.locator('.reference-writing>li')).toHaveCount(3);await expect(page.locator('.reply-writing>li')).toHaveCount(12);await page.getByRole('button',{name:'打印练习纸',exact:true}).click();await expect.poll(()=>page.evaluate(()=>printRequested)).toBe(true);await page.emulateMedia({media:'print'});await page.pdf({path:OUT+'/writing.pdf',format:'A4',printBackground:true});
});
test('理解题与综合配图逐幅留存未选、错误、修正截图',async({page})=>{
 test.setTimeout(150000);await page.setViewportSize({width:1280,height:1200});await story(page);await page.goto('/unit35-36/#learn/text');await page.locator('.stage-text').screenshot({path:OUT+'/story-complete.png'});await page.locator('.stage-text').getByRole('button',{name:'再看一遍',exact:true}).click();const text=page.locator('.stage-text');for(let i=0;i<6;i++)await text.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();await text.getByRole('button',{name:'看中文',exact:true}).last().click();await page.goto('/unit35-36/#learn/text');await page.screenshot({path:OUT+'/preview-desktop.png'});await text.screenshot({path:OUT+'/theatre-reviewed.png'});
 await page.goto('/unit35-36/#learn/roles');const r=page.locator('.stage-roles');const incorrect=['浮在河面上','the banks of the river','照片一','the park'];for(const [i,a]of ANSWERS.roles.entries()){await r.screenshot({path:OUT+'/roles-before-'+i+'.png'});await select(r,incorrect[i]);await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await r.screenshot({path:OUT+'/roles-wrong-'+i+'.png'});await r.getByRole('button',{name:'再试一次',exact:true}).click();await select(r,a);await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('答对了！');await r.screenshot({path:OUT+'/roles-correct-'+i+'.png'});await advance(r,i===3);}
});
test('缺一张新插图时保持准备页，恢复网络后完整进入',async({page})=>{
 test.setTimeout(60000);await page.route(/\/valley\.svg(?:\?|$)/,r=>r.abort());await page.goto('/lesson/unit35-36/#learn/words');await expect(page.locator('#courseLoader')).toBeVisible();await expect(page.getByRole('button',{name:'再试一次',exact:true})).toBeVisible({timeout:45000});await expect(page.locator('.stage-words')).not.toBeVisible();await page.unroute(/\/valley\.svg(?:\?|$)/);await page.getByRole('button',{name:'再试一次',exact:true}).click();await expect(page.locator('#courseLoader')).toBeHidden({timeout:45000});await expect.poll(()=>page.locator('.stage-words img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);
});

test('浏览器禁止常驻缓存时，对照图仍保持可读尺寸',async({browser})=>{
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width:390,height:900}});try{const page=await context.newPage();await page.goto('/lesson/unit35-36/#learn/observe');await expect(page.locator('#courseLoader')).toBeHidden({timeout:60000});const room=page.locator('.stage-observe');await select(room,'照片三');await room.getByRole('button',{name:'检查答案',exact:true}).click();await advance(room,false);await expect.poll(()=>room.locator('.practice-scene').evaluate(e=>e.complete&&e.naturalWidth>0&&e.getBoundingClientRect().height>300)).toBe(true);await room.screenshot({path:OUT+'/routes-fallback-390.png'});}finally{await context.close();}
});
test('缓存降级仍可导出完整人物和徽章的证书',async({browser})=>{
 test.setTimeout(90000);const context=await browser.newContext({serviceWorkers:'block'});try{const page=await context.newPage();await complete(page,'/lesson');await page.getByRole('button',{name:'领取单元证书',exact:true}).click();const dialog=page.getByRole('dialog',{name:'村庄相册纪念',exact:true});const download=page.waitForEvent('download',{timeout:15000});await dialog.getByRole('button',{name:'保存图片',exact:true}).click();const [file]=await Promise.all([download,expect(dialog.getByRole('status')).toContainText('纪念图片已保存')]);await file.saveAs(OUT+'/certificate-fallback.png');}finally{await context.close();}
});
