'use strict';
const {test,expect}=require('@playwright/test'),fs=require('node:fs/promises');
const {DIALOGUE,ANSWERS,WRONG,select,advance,activity,story,complete}=require('../support/unit33-34-flow');
const OUT='output/playwright/unit33-34';test.use({reducedMotion:'reduce'});test.beforeAll(()=>fs.mkdir(OUT,{recursive:true}));
test('横幅入口、22张词卡音标与释义完整，刷新与回首页继续',async({page})=>{
 await page.goto('/');await page.getByRole('link',{name:'开始学习：晴天河畔发现之旅',exact:true}).click();await expect(page).toHaveURL(/unit33-34\/#learn\/words$/);const room=page.locator('.stage-words');
 for(let g=0;g<4;g++){await expect(room.locator('.unit-word')).toHaveCount(g===3?4:6);for(const card of await room.locator('.unit-word').all()){await expect(card.locator('.word-phonetic')).toBeVisible();await expect.poll(()=>card.locator('img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);const before=await card.boundingBox();await card.click();await expect(card.locator('.word-meaning')).toBeVisible();expect((await card.boundingBox()).height).toBe(before.height);await card.click();}if(g<3)await room.getByRole('button',{name:'下一组词卡',exact:true}).click();}
 await page.reload();await expect(room.locator('#wordPageProgress')).toHaveText('4 / 4');await room.getByRole('button',{name:'下一站：单词寻宝',exact:true}).click();await expect(page.locator('.stage-listen h3').first()).toBeInViewport();await page.getByRole('link',{name:'我的课程',exact:true}).click();await expect(page.getByRole('link',{name:'继续学习：晴天河畔发现之旅',exact:true})).toHaveAttribute('href','/unit33-34/#learn/listen');
});
test('断音完整33题与10句原文得到15星，纪念证书PNG与打印',async({page})=>{
 test.setTimeout(180000);await page.setViewportSize({width:1280,height:1200});const errors=[],voices=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/\/(audio|voices)\//.test(r.url()))voices.push(r.url());});await page.route(/\.(mp3|ogg|wav)(\?|$)/,r=>r.abort());await page.addInitScript(()=>{globalThis.voiceCalls=0;speechSynthesis.speak=()=>globalThis.voiceCalls++;HTMLMediaElement.prototype.play=()=>Promise.reject(Error('sound unavailable'));});
 await activity(page,'listen');await page.locator('.stage-listen').screenshot({path:OUT+'/finish-listen.png'});await story(page);await page.goto('/unit33-34/#learn/text');await page.locator('.stage-text').screenshot({path:OUT+'/finish-text.png'});for(const id of ['roles','observe','be','trans','exam']){await activity(page,id);await page.locator('.stage-'+id).screenshot({path:OUT+'/finish-'+id+'.png'});}await page.goto('/unit33-34/#learn/certificate');await expect(page.locator('#starCount')).toHaveText('15');await page.getByRole('textbox',{name:'证书上的名字',exact:true}).fill('河畔小观察员');await page.getByRole('button',{name:'领取单元证书',exact:true}).click();const dialog=page.getByRole('dialog',{name:'河畔发现纪念',exact:true});await expect(dialog).toContainText('完成 Lesson 33–34 课堂配套练习');await expect(dialog).not.toContainText('听力');const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'保存图片',exact:true}).click();await(await pending).saveAs(OUT+'/certificate.png');await page.screenshot({path:OUT+'/certificate-page.png'});await page.emulateMedia({media:'print'});await page.pdf({path:OUT+'/certificate.pdf',format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});await page.keyboard.press('Escape');await page.reload();await expect(page.locator('#starCount')).toHaveText('15');await expect(page.getByRole('textbox',{name:'证书上的名字',exact:true})).toHaveValue('河畔小观察员');expect(errors).toEqual([]);expect(voices).toEqual([]);expect(await page.evaluate(()=>voiceCalls)).toBe(0);
});
test('部分配对不能提交、错答不揭底，刷新后可原题修正',async({page})=>{
 await page.goto('/unit33-34/#learn/listen');const r=page.locator('.stage-listen');await select(r,{match:[['day','云']]});await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await select(r,{match:[['cloud','一天'],['sky','天空']]});await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await expect(r.locator('.is-correct')).toHaveCount(0);await page.reload();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await r.getByRole('button',{name:'再试一次',exact:true}).click();await select(r,{match:[['day','一天'],['cloud','云']]});await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('答对了！');await advance(r,false);await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
});
test('叙述历史、最长句和翻译内部滚动，按钮稳定；末句不自动完成',async({page})=>{
 await page.goto('/unit33-34/#learn/roles');await page.getByRole('button',{name:'先看课文',exact:true}).click();const r=page.locator('.stage-text');let top;
 for(let i=0;i<10;i++){await r.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();await expect(r.locator('.btext span')).toHaveText(DIALOGUE.slice(0,i+1));if([0,1,5,7,9].includes(i)){await r.getByRole('button',{name:'看中文',exact:true}).last().click();await r.screenshot({path:OUT+'/story-'+i+'.png'});}const y=await r.locator('.stage-ctrl').evaluate(e=>e.getBoundingClientRect().top+scrollY);if(top===undefined)top=y;else expect(Math.abs(y-top)).toBeLessThan(2);if(i===5){await page.reload();await expect(r.locator('.btext')).toHaveCount(6);}}
 await expect(page.locator('#starCount')).toHaveText('0');await r.getByRole('button',{name:'完成课文',exact:true}).click();await expect(page.locator('#starCount')).toHaveText('1');await r.getByRole('button',{name:'再看一遍',exact:true}).click();await page.reload();await expect(r.locator('.btext')).toHaveCount(0);
});
test('综合13题逐题答错和修正，暂停续答、撤回词块、末题确认与重练',async({page})=>{
 test.setTimeout(180000);await page.goto('/unit33-34/#learn/exam');const r=page.locator('.stage-exam');
 for(const [i,answer]of ANSWERS.exam.entries()){
  await expect(r).toContainText(`第 ${i+1} / 13 题`);await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await select(r,WRONG[i]);await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await expect(r.locator('.is-correct')).toHaveCount(0);if([2,8,11].includes(i))await r.screenshot({path:OUT+'/exam-wrong-'+i+'.png'});if(i===12){await page.reload();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');}
  await r.getByRole('button',{name:'再试一次',exact:true}).click();if(Array.isArray(answer)){const chosen=r.getByRole('group',{name:'已选词块',exact:true});while(await chosen.getByRole('button').count())await chosen.getByRole('button').first().click();}await select(r,answer);
  if(i===0){await r.getByRole('button',{name:'暂停，稍后继续',exact:true}).click();await page.reload();await expect(r).toContainText('已暂停 · 第 1 / 13 题');await r.getByRole('button',{name:'继续挑战',exact:true}).click();await expect(r.getByRole('button',{name:answer,exact:true})).toHaveAttribute('aria-pressed','true');}
  await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('答对了！');await expect(r.getByRole('progressbar')).toHaveAttribute('aria-valuenow',String(i+1));if(i===12)await expect(page.locator('#starCount')).toHaveText('0');await advance(r,i===12,true);
 }
 await expect(r).toContainText('修正后完成 13 题');await r.screenshot({path:OUT+'/challenge-complete.png'});await expect(page.locator('#starCount')).toHaveText('3');await r.getByRole('button',{name:'再练一轮',exact:true}).click();await page.reload();await expect(r.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await expect(r.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
});
for(const width of [320,390,768,1280])test(`宽度${width}画卷、找船未选错误正确、动作册词卡无溢出`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:width>=768?1200:900});await page.goto('/unit33-34/#learn/text');const r=page.locator('.stage-text');for(let i=0;i<2;i++)await r.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();await r.getByRole('button',{name:'看中文',exact:true}).last().click();await r.screenshot({path:OUT+'/theatre-'+width+'.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);expect(await r.locator('.dialogue-log').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThan(2);
 await page.goto('/unit33-34/#learn/observe');const o=page.locator('.stage-observe');await o.screenshot({path:OUT+'/find-before-'+width+'.png'});await expect(o.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();for(const name of ['1号船','2号船','3号船']){const box=await o.getByRole('button',{name,exact:true}).boundingBox();expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);}await o.getByRole('button',{name:'2号船',exact:true}).click();await o.getByRole('button',{name:'检查答案',exact:true}).click();await expect(o.getByRole('status')).toHaveText('再看看，试一次。');await o.screenshot({path:OUT+'/find-wrong-'+width+'.png'});await page.reload();await expect(o.getByRole('status')).toHaveText('再看看，试一次。');await o.getByRole('button',{name:'再试一次',exact:true}).press('Enter');await o.getByRole('button',{name:'1号船',exact:true}).press('Enter');await o.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect(o.getByRole('status')).toHaveText('答对了！');await o.screenshot({path:OUT+'/find-correct-'+width+'.png'});
 await page.goto('/unit33-34/#learn/models');const m=page.locator('.stage-models');for(let i=0;i<4;i++){await expect(m.locator('.reference-card')).toHaveCount(3);await expect.poll(()=>m.locator('img').evaluateAll(imgs=>imgs.every(im=>im.complete&&im.naturalWidth>0))).toBe(true);await m.screenshot({path:OUT+'/gallery-'+width+'-'+i+'.png'});if(i<3)await m.getByRole('button',{name:'下一页动作',exact:true}).click();}await expect(m.locator('.reference-card').last()).toContainText('The children are jumping off the wall.');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
 await page.goto('/unit33-34/#learn/words');const words=page.locator('.stage-words');for(let i=0;i<2;i++)await words.getByRole('button',{name:'下一组词卡',exact:true}).click();await words.getByRole('button',{name:'aeroplane',exact:true}).click();await words.screenshot({path:OUT+'/words-'+width+'.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
});
test('缓存首次准备、热重访离线翻卡及画册图片就绪',async({page,context})=>{
 test.setTimeout(120000);await page.goto('/lesson/unit33-34/#learn/words');await expect(page.locator('#courseLoader')).toBeHidden({timeout:60000});await page.locator('.stage-words').getByRole('button',{name:'下一组词卡',exact:true}).click();await context.setOffline(true);await page.reload();await expect(page.locator('#courseLoader')).toBeHidden({timeout:30000});await expect(page.locator('#wordPageProgress')).toHaveText('2 / 4');await page.goto('/lesson/unit33-34/#learn/models');for(let i=0;i<3;i++)await page.locator('.stage-models').getByRole('button',{name:'下一页动作',exact:true}).click();await expect.poll(()=>page.locator('.stage-models .reference-card img').evaluateAll(imgs=>imgs.every(im=>im.complete&&im.naturalWidth>0))).toBe(true);await context.setOffline(false);
});
test('正常反馈音与键盘作答；教材A5/B12纸笔练习完整打印',async({page})=>{
 await page.addInitScript(()=>{globalThis.completedSounds=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){this.addEventListener('ended',()=>globalThis.completedSounds.push(this.currentSrc),{once:true});return play.call(this);};globalThis.print=()=>globalThis.printRequested=true;});await page.goto('/unit33-34/#learn/observe');const o=page.locator('.stage-observe');await o.getByRole('button',{name:'3号船',exact:true}).press('Enter');await o.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>completedSounds.length)).toBe(1);await o.getByRole('button',{name:'再试一次',exact:true}).press('Enter');await o.getByRole('button',{name:'1号船',exact:true}).press('Enter');await o.getByRole('button',{name:'检查答案',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>completedSounds.length)).toBe(2);await page.goto('/unit33-34/#learn/certificate');await page.locator('#unitWriting>summary').click();await expect(page.locator('.reference-writing>li')).toHaveCount(5);await expect(page.locator('.reply-writing>li')).toHaveCount(12);await page.getByRole('button',{name:'打印练习纸',exact:true}).click();await expect.poll(()=>page.evaluate(()=>printRequested)).toBe(true);await page.emulateMedia({media:'print'});await page.pdf({path:OUT+'/writing.pdf',format:'A4',printBackground:true});
});
test('新插图题逐幅核对未选、错误、修正状态；长选项和按句翻译可读',async({page})=>{
 test.setTimeout(90000);await page.setViewportSize({width:1280,height:1200});await story(page);await page.goto('/unit33-34/#learn/text');await page.locator('.stage-text').screenshot({path:OUT+'/story-complete.png'});await page.locator('.stage-text').getByRole('button',{name:'再看一遍',exact:true}).click();const text=page.locator('.stage-text');for(let i=0;i<2;i++)await text.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();await text.getByRole('button',{name:'看中文',exact:true}).last().click();await page.goto('/unit33-34/#learn/text');await page.screenshot({path:OUT+'/preview-desktop.png'});await text.screenshot({path:OUT+'/theatre-reviewed.png'});
 await page.goto('/unit33-34/#learn/roles');const r=page.locator('.stage-roles');const incorrect=['the boats','the river','Sally → an aeroplane; Tim → a big ship','画面一'];for(const [i,a]of ANSWERS.roles.entries()){await r.screenshot({path:OUT+'/roles-before-'+i+'.png'});await select(r,incorrect[i]);await r.getByRole('button',{name:'检查答案',exact:true}).click();await expect(r.getByRole('status')).toHaveText('再看看，试一次。');await r.screenshot({path:OUT+'/roles-wrong-'+i+'.png'});await r.getByRole('button',{name:'再试一次',exact:true}).click();await select(r,a);await r.getByRole('button',{name:'检查答案',exact:true}).click();await r.screenshot({path:OUT+'/roles-correct-'+i+'.png'});await advance(r,i===3);}
 await page.goto('/unit33-34/#learn/observe');const o=page.locator('.stage-observe');await select(o,'1号船');await o.getByRole('button',{name:'检查答案',exact:true}).click();await advance(o,false);await o.screenshot({path:OUT+'/plane-before.png'});await select(o,{cloze:['on']});await o.getByRole('button',{name:'检查答案',exact:true}).click();await o.screenshot({path:OUT+'/plane-wrong.png'});await o.getByRole('button',{name:'再试一次',exact:true}).click();await select(o,{cloze:['over']});await o.getByRole('button',{name:'检查答案',exact:true}).click();await o.screenshot({path:OUT+'/plane-correct.png'});await expect(o.getByRole('status')).toHaveText('答对了！');
 await page.goto('/unit33-34/#learn/be');const b=page.locator('.stage-be');await select(b,ANSWERS.be[0]);await b.getByRole('button',{name:'检查答案',exact:true}).click();await advance(b,false);await b.screenshot({path:OUT+'/waiting-before.png'});await select(b,'He is waiting for a bus.');await b.getByRole('button',{name:'检查答案',exact:true}).click();await b.screenshot({path:OUT+'/waiting-wrong.png'});await b.getByRole('button',{name:'再试一次',exact:true}).click();await select(b,ANSWERS.be[1]);await b.getByRole('button',{name:'检查答案',exact:true}).click();await b.screenshot({path:OUT+'/waiting-correct.png'});await expect(b.getByRole('status')).toHaveText('答对了！');
});
