'use strict';
const {test,expect}=require('@playwright/test');
const {completeUnit1112,completeActivity}=require('../support/unit11-12-flow');
test.use({reducedMotion:'reduce',actionTimeout:5000});
test('物主选项限定为教材已教的 my、your、his、her，不引入新结构',async({page})=>{
 await page.goto('/unit11-12/#learn/owner');expect((await page.locator('.stage-owner .practice-options button').allTextContents()).sort()).toEqual(['her','his','my','your']);
});
test('从音标图鉴开始，浏览16句并完成23题才取得15星课堂配套证书',async({page})=>{
 test.setTimeout(210000);await page.goto('/unit11-12/');await expect(page).toHaveTitle('失物招领小侦探 · Lesson 11–12');
 await page.getByRole('button',{name:'开始冒险',exact:true}).click();await expect(page).toHaveURL(/#learn\/words$/);
 const room=page.locator('.stage-words'),word=room.getByRole('button',{name:'whose',exact:true});await expect(word).toContainText('/huːz/');await word.click();await expect(word.locator('.word-meaning')).toBeVisible();await expect(word).not.toContainText('录音暂时');
 for(let i=0;i<2;i++)await room.getByRole('button',{name:'下一组词卡',exact:true}).click();await expect(room.locator('.unit-word')).toHaveCount(6);await room.getByRole('button',{name:'下一站：单词寻宝',exact:true}).click();await expect(page.locator('.stage-listen')).toContainText('第 1 / 13 题');
 await page.goto('/unit11-12/#learn/certificate');await expect(page.getByRole('button',{name:'领取单元证书',exact:true})).toBeDisabled();await completeUnit1112(page);
 await page.getByRole('textbox',{name:'证书上的名字',exact:true}).fill('归还小能手');await page.getByRole('button',{name:'领取单元证书',exact:true}).click();const dialog=page.getByRole('dialog',{name:'失物招领小侦探纪念',exact:true});await expect(dialog.locator('#certificateName')).toHaveText('归还小能手');const day=await dialog.locator('#certificateDate').innerText();
 await dialog.screenshot({path:'output/playwright/unit11-12/certificate-desktop.png'});const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'保存图片',exact:true}).click();await(await download).saveAs('output/playwright/unit11-12/certificate-saved.png');const pdf=await page.pdf({path:'output/playwright/unit11-12/certificate-print.pdf',preferCSSPageSize:true,printBackground:true});expect(pdf.toString('latin1').match(/\/Type \/Page\b/g)).toHaveLength(1);
 await page.keyboard.press('Escape');await page.reload();await page.getByRole('button',{name:'领取单元证书',exact:true}).click();await expect(dialog.locator('#certificateDate')).toHaveText(day);await page.keyboard.press('Escape');for(const other of ['unit1-2','unit3-4','unit5-6','unit7-8','unit9-10','unit49-50']){await page.goto('/'+other+'/#learn/certificate');await expect(page.locator('#starCount')).toHaveText('0');}
});

test('首页和 lesson 子目录进入新单元，独立恢复草稿并定位同一地址',async({page})=>{
 const failed=[];page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});await page.goto('/lesson/');await page.getByRole('link',{name:'开始学习：失物招领小侦探',exact:true}).click();await expect(page).toHaveURL(/\/lesson\/unit11-12\/#learn\/words$/);
 await page.getByRole('link',{name:'谁的说清楚',exact:true}).click();const room=page.locator('.stage-owner');await room.getByRole('button',{name:'her',exact:true}).click();await page.locator('#startBtn').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'继续冒险',exact:true}).click();await expect(room.getByRole('heading').first()).toBeInViewport();
 await page.getByRole('link',{name:'我的课程',exact:true}).click();await expect(page.getByRole('link',{name:'继续学习：失物招领小侦探',exact:true})).toHaveAttribute('href','/lesson/unit11-12/#learn/owner');await expect(page.getByRole('link',{name:'开始学习：街角问候站',exact:true})).toBeVisible();await page.getByRole('link',{name:'继续学习：失物招领小侦探',exact:true}).click();await expect(room.getByRole('button',{name:'her',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.goto('/unit11-12/#learn/owner');await expect(room.getByRole('button',{name:'her',exact:true})).toHaveAttribute('aria-pressed','false');expect(failed).toEqual([]);
});

test('纸笔保留教材 A 四题与 B 十二题，真实打印一张 A4 且每组有三行书写区',async({page})=>{
 await page.goto('/unit11-12/#learn/certificate');await page.getByText('和朋友再试试',{exact:true}).click();await expect(page.locator('.reference-writing li')).toHaveText(['Stella is here. That is ___ car.（车主 Stella · she）','Excuse me, Steven. Is this ___ umbrella?（正对 Steven 说话）','I am an air hostess. ___ name is Britt.（Britt 自我介绍）','Paul is here, too. That is ___ coat.（物主 Paul · he）']);
 await expect(page.locator('.reply-writing li>span:first-child')).toHaveText(['handbag / Stella · she','car / Paul · he','coat / Sophie · she','umbrella / Steven · he','pen / my son · he','dress / my daughter · she','suit / my father · he','skirt / my mother · she','blouse / my sister · she','tie / my brother · he','pen / Sophie · she','pencil / Hans · he']);await page.evaluate(()=>{window.print=()=>{};});await page.getByRole('button',{name:'打印练习纸',exact:true}).click();await page.emulateMedia({media:'print',reducedMotion:'reduce'});
 for(const row of await page.locator('.reply-writing li').all()){await expect(row).toBeVisible();await expect(row.locator('.writing-rule')).toHaveCount(3);expect(await row.evaluate(el=>[...el.querySelectorAll('.writing-rule')].every(line=>line.getBoundingClientRect().height>=22&&line.clientWidth>=el.clientWidth*.9))).toBe(true);}
 const pdf=await page.pdf({path:'output/playwright/unit11-12/writing-print.pdf',preferCSSPageSize:true,printBackground:true});expect(pdf.toString('latin1').match(/\/Type \/Page\b/g)).toHaveLength(1);
});

test('挑战错答、提示、暂停刷新与独立作答分别记录，不提前发证',async({page})=>{
 test.setTimeout(45000);await page.goto('/unit11-12/#learn/exam');const room=page.locator('.stage-exam'),check=room.getByRole('button',{name:'检查答案',exact:true});await room.getByRole('button',{name:'my sister · pen',exact:true}).click();await expect(check).toBeEnabled({timeout:10000});await check.click();await expect(room.getByRole('status')).toHaveText('再看看，试一次。');await room.getByRole('button',{name:'再试一次',exact:true}).click();await room.getByRole('button',{name:'my brother · pen',exact:true}).click();await expect(check).toBeEnabled({timeout:10000});await check.click();await room.getByRole('button',{name:'下一题',exact:true}).click();
 await room.getByRole('button',{name:'给点线索',exact:true}).click();await room.getByRole('button',{name:'请 Tim 确认',exact:true}).click();await room.getByRole('button',{name:'暂停，稍后继续',exact:true}).click();await page.reload();await room.getByRole('button',{name:'继续挑战',exact:true}).click();await expect(room.getByRole('button',{name:'请 Tim 确认',exact:true})).toHaveAttribute('aria-pressed','true');await check.click();await room.getByRole('button',{name:'下一题',exact:true}).click();await room.getByRole('button',{name:'her',exact:true}).click();await check.click();await room.getByRole('button',{name:'查看本次记录',exact:true}).click();await expect(room).toContainText('首次独立答对 1 / 3');await expect(room).toContainText('提示后完成 1 题 · 修正后完成 1 题');await page.goto('/unit11-12/#learn/certificate');await expect(page.locator('#starCount')).toHaveText('3');await expect(page.getByRole('button',{name:'领取单元证书',exact:true})).toBeDisabled();
});

test('内容升版只让改过的活动失效，另一个活动的草稿保留',async({page})=>{
 await page.goto('/unit11-12/#learn/owner');const owner=page.locator('.stage-owner');await owner.getByRole('button',{name:'her',exact:true}).click();await owner.getByRole('button',{name:'检查答案',exact:true}).click();await page.goto('/unit11-12/#learn/trans');const trans=page.locator('.stage-trans');await trans.getByRole('group',{name:'待选词块',exact:true}).getByRole('button',{name:'Whose',exact:true}).click();await page.route('**/unit11-12/content.js*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace("q('owner-her'","q('owner-her-revised'")});});await page.reload();await expect(trans.getByRole('group',{name:'已选词块',exact:true}).getByRole('button',{name:'撤回 Whose',exact:true})).toBeVisible();await page.goto('/unit11-12/#learn/owner');await expect(owner.getByRole('button',{name:'her',exact:true})).toHaveAttribute('aria-pressed','false');await expect(owner.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await expect(owner.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();
});

test('重开冒险包括新单元，取消保留而确认仅清理当前网站路径的记录',async({page})=>{
 await page.goto('/unit11-12/#learn/owner');const room=page.locator('.stage-owner');await room.getByRole('button',{name:'her',exact:true}).click();for(const path of ['unit1-2/#learn/ask','unit3-4/#learn/reply','unit5-6/#learn/refer','unit7-8/#learn/be','unit9-10/#learn/describe','unit11-12/#learn/owner','unit49-50/#learn/give'])await page.goto('/lesson/'+path);await page.goto('/lesson/');await page.getByRole('button',{name:'设备冒险设置',exact:true}).click();await page.getByRole('button',{name:'重开冒险',exact:true}).click();await page.getByRole('button',{name:'继续确认',exact:true}).click();await page.getByRole('button',{name:'取消重开',exact:true}).click();await page.getByRole('button',{name:'返回课程',exact:true}).click();await expect(page.getByRole('link',{name:'继续学习：失物招领小侦探',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'设备冒险设置',exact:true}).click();await page.getByRole('button',{name:'重开冒险',exact:true}).click();await page.getByRole('button',{name:'继续确认',exact:true}).click();await page.getByRole('button',{name:'确认重开',exact:true}).click();for(const name of ['礼貌小帮手','雨伞认领小帮手','新朋友见面会','新朋友采访站','街角问候站','失物招领小侦探'])await expect(page.getByRole('link',{name:'开始学习：'+name,exact:true})).toBeVisible();await page.goto('/unit11-12/#learn/owner');await expect(room.getByRole('button',{name:'her',exact:true})).toHaveAttribute('aria-pressed','true');
});

test('短屏单词练习末题与重练可操作，重练清本轮答案且保留已获星星',async({page})=>{
 test.setTimeout(90000);await page.setViewportSize({width:390,height:500});await completeActivity(page,'listen');const room=page.locator('.stage-listen');await expect(page.locator('#starCount')).toHaveText('3');await room.getByRole('button',{name:'再练一轮',exact:true}).click();await expect(room).toContainText('第 1 / 13 题');await expect(room.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await expect(room.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await expect(room.locator('.practice-options [aria-pressed="true"]')).toHaveCount(0);await page.reload();await expect(room.getByRole('button',{name:'检查答案',exact:true})).toBeDisabled();await expect(page.locator('#starCount')).toHaveText('3');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
