'use strict';
const {test,expect}=require('@playwright/test');
const {adminLogin,createStudent,studentLogin}=require('./helpers');
const {complete}=require('../support/unit37-38-flow');
test('37–38默认不开放、单课授权登录通关同步，换设备续用证书，其他班级直链拒绝',async({page,browser})=>{
 test.setTimeout(180000);await adminLogin(page);const account=await createStudent(page,'工坊验收班','工坊同学',[/Lesson 37–38 /]);const first=await studentLogin(browser,account);let second,closed;
 try{await expect(first.page.locator('.featured-course')).toHaveCount(1);await expect(first.page.locator('.featured-course h2')).toHaveText('书架制作小工坊');await expect(first.page.getByRole('link',{name:'开始学习：书架制作小工坊',exact:true})).toHaveAttribute('href','/lesson/unit37-38/#learn/words');await complete(first.page,'/lesson');await first.page.getByRole('textbox',{name:'证书上的名字',exact:true}).fill('工坊同学');await first.page.getByRole('button',{name:'领取单元证书',exact:true}).click();await first.page.keyboard.press('Escape');await expect(first.page.locator('#studentSyncStatus')).toHaveText('学习成果已同步');await first.page.getByRole('link',{name:'我的课程',exact:true}).click();await first.page.screenshot({path:'output/playwright/unit37-38/auth-banner.png',fullPage:true});await expect(first.page.locator('.featured-course')).toContainText('15 / 15');
 second=await studentLogin(browser,account);await expect(second.page.locator('.featured-course')).toContainText('15 / 15');await second.page.goto('/lesson/unit37-38/#learn/certificate');await expect(second.page.getByRole('textbox',{name:'证书上的名字',exact:true})).toHaveValue('工坊同学');await expect(second.page.getByRole('button',{name:'领取单元证书',exact:true})).toBeEnabled();
 await page.goto('/lesson/admin/');const other=await createStudent(page,'只有花园的班','小河',[/Lesson 31–32 /]);await expect(page.getByRole('checkbox',{name:/Lesson 37–38 /})).not.toBeChecked();closed=await studentLogin(browser,other);await expect(closed.page.locator('[data-unit="unit37-38"]')).toHaveCount(0);await closed.page.goto('/lesson/unit37-38/');await expect(closed.page.getByRole('heading',{name:'这节课还没向你的班级开放',exact:true})).toBeVisible();await second.page.goto('/lesson/lesson49/');await expect(second.page.getByRole('heading',{name:'这节课已下架',exact:true})).toBeVisible();
 }finally{await first.context.close();await second?.context.close();await closed?.context.close();}
});
test('根目录真实登录通关、刷新恢复，旧lesson入口不恢复',async({browser})=>{
 test.setTimeout(180000);const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const {createApp}=require('../../server/app'),{openStore}=require('../../server/store');const {signIn}=require('./helpers');const directory=await fs.mkdtemp(path.join(os.tmpdir(),'canran-workshop-root-test-'));const store=openStore(directory);store.setAdmin('teacher','Test-only-classroom-2026!');store.close();const origin=require('../support/login-test-ports').origin(4243);const server=await createApp({dataDir:directory,origin,basePath:'/'});await new Promise(resolve=>server.listen(require('../support/login-test-ports').port(4243),'127.0.0.1',resolve));const context=await browser.newContext({baseURL:origin});
 try{const p=await context.newPage();await adminLogin(p,'/');const account=await createStudent(p,'根目录工坊班','小溪',[/Lesson 37–38 /]);await signIn(p,account,'/');await p.setViewportSize({width:1280,height:720});await p.goto('/unit37-38/#learn/text');const stage=p.locator('.stage-text');
 for(let i=0;i<14;i++)await stage.getByRole('button',{name:i?'下一句':'开始看课文',exact:true}).click();await stage.getByRole('button',{name:'看中文',exact:true}).last().click();await expect(stage.locator('.bubble-row').last().locator('.btext')).toBeInViewport({ratio:0.99});await expect(stage.getByRole('button',{name:'下一句',exact:true})).toBeInViewport({ratio:0.99});await p.screenshot({path:'output/playwright/unit37-38/auth-short-screen.png'});await stage.getByRole('button',{name:'从头看',exact:true}).click();await complete(p);await expect(p.locator('#studentSyncStatus')).toHaveText('学习成果已同步');await p.reload();await expect(p.locator('#starCount')).toHaveText('15');await p.goto('/lesson/');await expect(p.getByRole('heading',{name:'旧课程入口已移除',exact:true})).toBeVisible();}finally{await context.close();await new Promise(resolve=>server.close(resolve));await fs.rm(directory,{recursive:true,force:true});}
});
