'use strict';
const {test,expect}=require('@playwright/test');
const {adminLogin,createStudent,studentLogin}=require('./helpers');
const {complete}=require('../support/unit35-36-flow');
test('35–36默认不开放、单课授权登录通关同步，换设备续用证书，其他班级直链拒绝',async({page,browser})=>{
 test.setTimeout(180000);await adminLogin(page);const account=await createStudent(page,'村庄验收班','村庄同学',[/Lesson 35–36 /]);const first=await studentLogin(browser,account);let second,closed;
 try{await expect(first.page.locator('.featured-course')).toHaveCount(1);await expect(first.page.locator('.featured-course h2')).toHaveText('村庄相册探险');await expect(first.page.getByRole('link',{name:'开始学习：村庄相册探险',exact:true})).toHaveAttribute('href','/lesson/unit35-36/#learn/words');await complete(first.page,'/lesson');await first.page.getByRole('textbox',{name:'证书上的名字',exact:true}).fill('村庄同学');await first.page.getByRole('button',{name:'领取单元证书',exact:true}).click();await first.page.keyboard.press('Escape');await expect(first.page.locator('#studentSyncStatus')).toHaveText('学习成果已同步');await first.page.getByRole('link',{name:'我的课程',exact:true}).click();await first.page.screenshot({path:'output/playwright/unit35-36/auth-banner.png',fullPage:true});await expect(first.page.locator('.featured-course')).toContainText('15 / 15');
 second=await studentLogin(browser,account);await expect(second.page.locator('.featured-course')).toContainText('15 / 15');await second.page.goto('/lesson/unit35-36/#learn/certificate');await expect(second.page.getByRole('textbox',{name:'证书上的名字',exact:true})).toHaveValue('村庄同学');await expect(second.page.getByRole('button',{name:'领取单元证书',exact:true})).toBeEnabled();
 await page.goto('/lesson/admin/');const other=await createStudent(page,'只有花园的班','小河',[/Lesson 31–32 /]);await expect(page.getByRole('checkbox',{name:/Lesson 35–36 /})).not.toBeChecked();closed=await studentLogin(browser,other);await expect(closed.page.locator('[data-unit="unit35-36"]')).toHaveCount(0);await closed.page.goto('/lesson/unit35-36/');await expect(closed.page.getByRole('heading',{name:'这节课还没向你的班级开放',exact:true})).toBeVisible();await second.page.goto('/lesson/lesson49/');await expect(second.page.getByRole('heading',{name:'这节课已下架',exact:true})).toBeVisible();
 }finally{await first.context.close();await second?.context.close();await closed?.context.close();}
});
test('根目录真实登录通关、刷新恢复，旧lesson入口不恢复',async({browser})=>{
 test.setTimeout(180000);const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const {createApp}=require('../../server/app'),{openStore}=require('../../server/store');const {signIn}=require('./helpers');const directory=await fs.mkdtemp(path.join(os.tmpdir(),'canran-village-root-test-'));const store=openStore(directory);store.setAdmin('teacher','Test-only-classroom-2026!');store.close();const origin=require('../support/login-test-ports').origin(4238);const server=await createApp({dataDir:directory,origin,basePath:'/'});await new Promise(resolve=>server.listen(require('../support/login-test-ports').port(4238),'127.0.0.1',resolve));const context=await browser.newContext({baseURL:origin});
 try{const p=await context.newPage();await adminLogin(p,'/');const account=await createStudent(p,'根目录村庄班','小溪',[/Lesson 35–36 /]);await signIn(p,account,'/');await complete(p);await expect(p.locator('#studentSyncStatus')).toHaveText('学习成果已同步');await p.reload();await expect(p.locator('#starCount')).toHaveText('15');await p.goto('/lesson/');await expect(p.getByRole('heading',{name:'旧课程入口已移除',exact:true})).toBeVisible();}finally{await context.close();await new Promise(resolve=>server.close(resolve));await fs.rm(directory,{recursive:true,force:true});}
});
